### ISSUE TITLE
Update_Masternode does not download wallet

### ISSUE THREAD

**Issue by Gott3d** [BITCORNProject/BITCORN-Masternode-script#3]
Typo in Update_Masternode.sh and bitcorn_install.sh on line 9 
and in bitcorn_autoinstall.sh on line 187 with the file name containing "v" after the "-" (-v2.1.2-daemon.tar.gz).
Causing the wallet download to fail.

**Comment by spyhuntergenral** [comment]
+1
Same for the install script
URL needs to be : COIN_TGZ='https://github.com/BITCORNProject/BITCORN/releases/download/v2.1.2/BITCORN-2.1.2-daemon.tar.gz'

**Comment by cisnes** [comment]
Fixed
